.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. wispr_qt test_wispr_qt
clean: FORCE
	$(MAKE) -C .. wispr_qt_clean test_wispr_qt_clean
check: FORCE
	$(MAKE) -C .. test_wispr_qt_check
wispr-qt wispr-qt.exe: FORCE
	 $(MAKE) -C .. wispr_qt
